on:
  pull_request:
    types:
      [synchronize, opened]

jobs:
  Validate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório e entrar na branch
        uses: actions/checkout@v3

      - name: Instala o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Valida a cobertura dos testes
        run: mvn clean verify